sudo: required

services:
  - docker

before_install:
  - docker build -t narteysarso/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run narteysarso/react-test npm test --watchAll=false

after_success:
  - docker build -t narteysarso/multi-client ./client
  - docker build -t narteysarso/multi-nginx ./nginx
  - docker build -t narteysarso/multi-server ./server
  - docker build -t narteysarso/multi-worker ./worker
  # Login to hub.docker.com and push docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # 
  - docker push narteysarso/multi-client
  - docker push narteysarso/multi-nginx
  - docker push narteysarso/multi-server
  - docker push narteysarso/multi-worker
