name: Docker Deployment service

on: 
    push: 
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: docker build
          run: |
            docker build -t narteysarso/react-test -f Dockerfile.dev ./client
